const QUESTIONS = {
  level1: {
    name: "Perception",
    reminder: "Let go of your attachment to the outcome.",
    questions: [
      "Do you think I intimidate others? Why or why not?",
      "Do you think I've ever been fired from a job? If so, what for?",
      "What does my Instagram tell you about me?",
      "What is my body language telling you right now?",
      "What fast food restaurant do you think I'm most likely to drive through? What's my order?",
      "What do you think my go-to karaoke song is?",
      "What was your first impression of me?",
      "Do I seem like a coffee or tea person? Sweetened or unsweetened?",
      "What's the first thing you noticed about me?",
      "What subject do you think I thrived in at school? Did I fail any?",
      "What about me intrigues you?",
      "Do I seem like a morning person or a night owl? Why?",
      "What does my phone wallpaper tell you about me?",
      "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
      "What compliment do you think I hear the most?",
      "Do I look kind? Explain.",
      "What about me is most strange or unfamiliar to you?",
      "How likely am I to go camping? How high-maintenance is my set-up?",
      "What do you think is the hardest part of what I do for a living?",
      "What reality show do you think I'm most likely to binge watch? Explain.",
      "Do I seem like a cat or dog person?",
      "What do my shoes tell you about me?",
      "Do I seem like more of a creative or analytical type? Explain.",
      "How many speeding tickets do you think I've gotten in my life?",
      "Do I seem like someone who would get a name tattooed on myself? Why or why not?",
      "What do you think I'm most likely to splurge on?",
      "Finish the sentence: Just by looking at you I'd think ________.",
      "What character would I play in a movie?",
      "Do I remind you of anyone?",
      "Who do you think my celebrity crush is?",
      "Do you think I've ever checked an ex's phone for evidence?",
      "Do you think I was popular in school? Explain.",
      "On a scale of 1–10, how messy do you think my car is? (1 = cleanest, 10 = disaster.) Explain.",
      "Do you think I fall in love easily? Why or why not?",
      "Do you think plants thrive or die in my care? Explain.",
      "Do you think I'm usually early, on time, or late to events? Explain.",
      "If Myspace were still a thing, what would my profile song be?",
      "As a child, what do you think I wanted to be?"
    ],
    wildcards: [
      { text: "Maintain eye contact for thirty seconds. What did you notice?", timed: true, duration: 30 },
      { text: "Close your eyes. What colour is my shirt?", timed: false },
      { text: "Ask and answer the next question in a different accent. (Both players.)", timed: false },
      { text: "Think of your favourite childhood TV show of all time. On the count of 3, say it out loud! (Both players.)", timed: false },
      { text: "Draw a picture together.", timed: true, duration: 30 },
      { text: "Rate your dancing skills on a scale of 1–10. On the count of three, say your answers out loud! (Both players.)", timed: false },
      { text: "Draw a portrait of each other to the best of your ability. Then exchange.", timed: true, duration: 60 },
      { text: "Make an assumption about me. (Both players.)", timed: false },
      { text: "Close your eyes. What colour are my eyes?", timed: false },
      { text: "Write down something others would never guess about you just by looking at you. (Both players.) Compare.", timed: false },
      { text: "Think of your favourite brand of cereal. On the count of 3, say your answers out loud! (Both players.)", timed: false }
    ]
  },
  level2: {
    name: "Connection",
    reminder: "Be more interested in understanding others than being understood.",
    questions: [
      "What are you more afraid of — failure or success? And why?",
      "What is your first love's name and the reason you fell in love with them?",
      "If you have, when was the moment you realised you weren't invincible?",
      "What was your mother's name? And the most beautiful thing about her?",
      "How can you become a better person?",
      "Have you ever told someone 'I love you' but didn't mean it? If so, why?",
      "What is the last thing you lied to your mother about?",
      "What is a dream you've let go of?",
      "Are you missing anyone right now? Do you think they are missing you too?",
      "What's the most pain you've ever been in that wasn't physical?",
      "If you could get to know someone in your life on a deeper level, who would it be and why?",
      "What are you still trying to prove to yourself?",
      "Are you lying to yourself about anything?",
      "What lesson took you the longest to unlearn?",
      "Do you think the image you have of yourself matches the image others see?",
      "If you could have it your way: who would you be with? Where would you be? And what would you be doing?",
      "Is there a feeling you miss?",
      "What's been your happiest memory this past year?",
      "What's your father's name? And tell me one thing about him.",
      "What is something you wouldn't want to change about yourself?",
      "What title would you give this chapter in your life?",
      "What question are you trying to answer most in your life right now?",
      "What is a compliment you wish you received more frequently?",
      "What has been your earliest recollection of happiness?",
      "When was the last time you surprised yourself?",
      "How would you describe the feeling of being loved in one word?",
      "What part of your life works? What part of your life hurts?",
      "What do you crave more of?",
      "What's been the best compliment a stranger has ever given you?",
      "Have you changed your mind about anything recently?",
      "Describe your perfect day.",
      "What is the most unexplainable thing that's ever happened to you?",
      "What would your younger self not believe about your life today?",
      "Has a stranger ever changed your life?",
      "How are you, really?",
      "When you're asked how are you, how often do you answer truthfully?",
      "Finish the sentences: Strangers would describe me as ____. Only I know that I am ____."
    ],
    wildcards: [
      { text: "Press shuffle on your music library. Explain the first song that comes up!", timed: false },
      { text: "Draw your current mood. Then compare. (Both players.)", timed: false },
      { text: "Sing the chorus of your favourite song of all time. Get into it!", timed: false },
      { text: "Both players write the three most important things in life to you. Compare.", timed: true, duration: 30 },
      { text: "Create a secret handshake!", timed: false },
      { text: "Both players write an embarrassing fun fact about yourselves. Play rock, paper, scissors — loser must reveal.", timed: false },
      { text: "Show the first photo in your camera roll. Explain.", timed: false },
      { text: "Think of something you strongly dislike that most people love. On the count of 3, say it out loud! (Both players.)", timed: false },
      { text: "Questions are an art form. Create your own question.", timed: false },
      { text: "Staring contest. First to blink must reveal a personal problem and ask their partner for advice.", timed: false },
      { text: "Ask a question you'd be too afraid to ask. Something you wouldn't dare to ask.", timed: false },
      { text: "Admit something.", timed: false },
      { text: "Call someone you admire and tell them why you appreciate them. (Put them on speaker phone.)", timed: false },
      { text: "Swap sweaters with your partner.", timed: false }
    ]
  },
  level3: {
    name: "Reflection",
    reminder: null,
    questions: [
      "What do you think my superpower is?",
      "Based on what you know about me, do you have any Netflix recommendations?",
      "What do I need to hear right now?",
      "Based on what you've learned about me, does my social media accurately reflect who I am? Why or why not?",
      "What can I help you with?",
      "If we were in a band, what would our name be?",
      "If you could prescribe me one thing to do for the rest of this month, what would it be and why?",
      "What am I most qualified to give advice about?",
      "What about me is hardest for you to understand?",
      "Based on what you've learned about me, what book would you recommend I read?",
      "What do you think I fear the most?",
      "What do you admire most about me?",
      "What is a lesson you will take away from our conversation?",
      "What answer of mine made you light up?",
      "What do you think our most important similarity is?",
      "How does one earn your vulnerability? Have I earned it? How can I earn more?",
      "When in this game did you feel most connected to me?",
      "What do you recommend I let go of, if anything?",
      "What do you think I should know about myself that perhaps I'm unaware of?",
      "What has this conversation taught you about yourself?",
      "What would make you feel closer to me?",
      "What do you think my weakness is?",
      "Why do you think we met?",
      "How do our personalities complement each other?",
      "What parts of yourself do you see in me?",
      "When this game is over, what will you remember about me?",
      "In one word, how would you describe our conversation?",
      "In one word, describe how you feel right now.",
      "What can we create together?",
      "What question were you most afraid to answer?",
      "Do you believe everyone has a calling? If so, do you think I've found mine?",
      "What would be the perfect gift for me?",
      "What about me most surprised you?",
      "How would you describe me to a stranger?",
      "What do you think my defining characteristic is?"
    ],
    wildcards: [
      { text: "Write down one thing you want to let go of this year. Read it out loud, then rip it up together. (Both players.)", timed: false },
      { text: "Swap a song you think your partner might enjoy. (Both players.)", timed: false },
      { text: "Give your partner a compliment you don't think they hear enough.", timed: false },
      { text: "Take a selfie together.", timed: false },
      { text: "Admit something.", timed: false },
      { text: "Dare your partner to do something outside their comfort zone in the next week. (Both players.)", timed: false },
      { text: "Write down a goal for this year. Fold and exchange. Hold each other accountable. (Both players.)", timed: false },
      { text: "Both players write a note to your younger selves. Option to compare.", timed: true, duration: 60 },
      { text: "Give your partner a hug. Not the crappy kind — a warm, genuine one.", timed: false },
      { text: "Write a song about your partner. Then sing it aloud — get into it! (Both players.)", timed: true, duration: 30 },
      { text: "Both players share something you're most grateful for in this current moment.", timed: false },
      { text: "Create your own question. Make it count.", timed: false },
      { text: "Play rock, paper, scissors. Winner can ask their partner anything — loser must answer.", timed: false },
      { text: "Scroll through each other's Instagrams. Find the picture you feel best represents your partner's essence and explain why you chose it.", timed: false },
      { text: "Give each other nicknames.", timed: false }
    ]
  },
  finalCard: "Each player write a message to the other, fold and exchange. Open only once you two have parted."
}
